FairwindsOps/terraform-bastion

CHANGELOG.md
README.md
README.pre_tf_inputs.md
additional_user.tf
auto-scaling.tf
bastion-userdata.tmpl
example-usage
inputs.tf
launchconfig.tf

* A new `additional_users` module input allows specifying additional SSH users to be created. The available per-user fields are login, gecos (full name), shell, supplemental groups, and SSH authorized\_keys.
* A new `additional_user-data` input allows specifying content to add toward the end of EC2 User Data. The additional User Data is executed before additional users are added.
* The Auto Scaling Group (and its bastion EC2) will now be recreated when there is an update to the Launch Configuration. The new Auto Scaling Group will be created before the current one is deleted. Previously the EC2 would remain untouched, leaving its recycling to operator discretion.

Add `additional_user_data` and `additional_users` inputs, recreate ASG and EC2 on launch config updates

---

security-group.tf

In cases where an outside process tags the security group regarding
allowing SSH access from the Internet, these tags should be ignored and
left in place.

Ignore tags on the SSH security group

---

additional_user.tf
auto-scaling.tf
bastion-userdata.tmpl
inputs.tf
launchconfig.tf

Most important - export DEBIAN_FRONTEND=noninteractive
Also a terraform fmt and adding more dpkg options to the apt commands.

Fixing apt install prompt issues.  Fixes #6

---

CHANGELOG.md
README.md
README.pre_tf_inputs.md
ami.tf
inputs.tf

GovCloud had a different owner number for Canonical. Converted the hardcoded values to variables so they could be altered if necessary.

added variables for ami

---

CHANGELOG.md
README.md
iam.tf
inputs.tf

GovCloud requires a different ARN prefix. This enables someone to make that change if necessary.

make the ARN prefix a parameter

---

CHANGELOG.md
bastion-userdata.tmpl

This was tested with Brian in govcloud, verifying that the first bastion copies it's sshd host-keys to S3, and a new bastion EC2 copies the host-keys from S3.

Fix copying sshd host-keys to/from S3 in govcloud

---

CHANGELOG.md
inputs.tf
security-group.tf

Switching to standalone security group rules allows non-Terraform things
to manage rules in the bastion security group. This transition requires recreating
the security group.
The SSH ingress security group rule will not be created, if the `ssh_cidr_blocks` input is an empty list. This allows overriding the module default, if SSH ingress rules will be managed elsewhere.

Switch to standalone security group rules, make the SSH ingress rule optional

---

gcp/bastion-startup-script.tmpl

The script that registers the bastion hostname in Google DNS, had a hard-coded value (from testing) that kept it from matching a hostname from a previous bastion, and cleaning up that record.

Fix GCP DNS registration script to remove old host records

---

aws/Makefile
aws/README.md
gcp/Makefile
gcp/README.md

This fixes the arguments to the Docker invocation of terraform-docs,
which is run while constructing the ReadMe files.
Comments have been removed from the Makefiles which describe temporary use
of a Docker image, as running Docker is a good way to not require folks to have
terraform-docs installed.

Fix use of terraform-docs to construct module ReadMes

---

README.md
aws/CHANGELOG.md
aws/README.md
aws/ami.tf
aws/inputs.tf

This pull request adds support for AWS GovCloud by ensuring that a sensible default (Canonical, Inc's AMI owner ID in GovCloud) is used for searching for Canonical AMIs when the `arn_prefix` variable indicates that the bastion should be deployed into an AWS partition other than the regular AWS commercial one.

Conditionally set AMI data source to search in GovCloud.

---

aws/CHANGELOG.md
aws/launchconfig.tf

I ran into another problem with bastions in GovCloud: the `aws_launch_configuration` resource for the bastion is unconditionally setting its `associate_public_ip_address` argument to `true` in the HCL source. While this works for the AWS commercial partition, the GovCloud partition refuses to launch instances from launch configurations configured in this way with the error:
```
The requested configuration is currently not supported.
```
There are actually three possible values for this argument in the AWS Management Console:
1. the default, which leaves the decision of whether or not to associate a public IP address to the subnet in which the instance was launched (yes for a public subnet, no for a private subnet),
2. a value called "every" (which maps to `true` in HCL), which is what the …

Bastions are always launched in public subnets, so this is not needed.

---

aws/CHANGELOG.md
aws/bastion-userdata.tmpl
gcp/CHANGELOG.md
gcp/bastion-startup-script.tmpl

Move the apt-get upgrade portion of the userdata script to run as an `at` job so as not to risk having one of the upgrades restart the startup script.

Userdata script updates for both AWS and GCP

---

aws/CHANGELOG.md
aws/versions.tf
gcp/CHANGELOG.md
gcp/versions.tf

- introduces breaking change between 0.12 to 0.13+
- terraform version must be >=0.13

Update required providers to format for v0.13+

---

aws/README.md
aws/inputs.tf
aws/launchconfig.tf
aws/outputs.tf
aws/ssh-keypair.tf

This field doesn't seems to be mandatory for those using additional_users features

Make ssh_public_key_file optional

---

aws/CHANGELOG.md
aws/README.md
aws/bastion-userdata.tmpl
aws/inputs.tf
aws/launchconfig.tf

This PR fixes issue https://github.com/FairwindsOps/terraform-bastion/pull/54#issuecomment-1014389472
Allow end user to add commands in user_data after additional users are created.
New input named additional_user_data_end.

add additional_user_data_end input

---

aws/CHANGELOG.md
aws/README.md
aws/inputs.tf
aws/launchconfig.tf

add `ssh_key_name` input to use a `aws_key_pair` resource provided by user

---

aws/CHANGELOG.md
aws/bastion-userdata.tmpl

This avoid cloud-init status to report an error.
This PR fixes issue #66
Change the last command for UserData script to exit with code 0

make userdata exit with code 0 when no reboot is required

---

aws/CHANGELOG.md
aws/README.md
aws/bastion-userdata.tmpl
aws/iam.tf
aws/inputs.tf

This PR fixes issue https://github.com/FairwindsOps/terraform-bastion/pull/51
This is same as https://github.com/FairwindsOps/terraform-bastion/pull/51, but doesn't contains the Load Balancer part. Along with #61, end user could bring it's own load balancer to publish the bastion.

make route53_zone_id optional

---

aws/CHANGELOG.md
aws/README.md
aws/auto-scaling.tf
aws/outputs.tf

This PR fixes issue https://github.com/FairwindsOps/terraform-bastion/pull/51#issuecomment-1015478107
Output autoscaling group information for end user to attach a custom or existing load balancer.

add autoscaling_group_id and autoscaling_group_arn outputs

---

gcp/iam.tf

Corrects the project variable type in iam.tf.
Use data.google_project.project.id in place of data.google_project.project.number

Fix iam.tf project variable type

---

gcp/README.md
gcp/inputs.tf
gcp/instance-template.tf

This PR fixes #
To enable the use of shielded_boot and confidential_compute for the bastion host, in gcp.
Added `enable_secure_boot`, `enable_confidential_compute` and `on_host_maintenance` variables to allow enabling of all these features without changing the default behavior.
N/A

Enable shielded nodes and confidential nodes GCP options

---

aws/README.md
aws/auto-scaling.tf
aws/inputs.tf
aws/launchconfig.tf

* [ x ] I have signed the CLA
* [ x ] I have updated/added any relevant documentation
Made root volume type configurable for AWS bastion.
Not setting the default to gp3.

Upgrade AWS root volume to gp3 (it's cheaper)

---

aws/auto-scaling.tf
aws/inputs.tf
gcp/compute-image.tf
gcp/inputs.tf

This PR fixes #
18.04 is EOL
Select latest applicable 20.04 LTS release by default.

Default bastion to 20.04

---

aws/auto-scaling.tf
aws/bastion-userdata.tmpl
aws/inputs.tf
aws/launchtemplate.tf

This PR updates the AWS bastion to use Ubuntu 22.04 AMIs by default, and changes from using a launch configuration to a launch template.
To update the Bastion to use launch templates, as well as the Ubuntu 22.04 AMI.

Update aws bastion to use ubuntu 22.04 and launch templates

---

aws/auto-scaling.tf
aws/bastion-userdata.tmpl
aws/inputs.tf
aws/launchtemplate.tf

This PR fixes #
The aws terraform provider now defaults EC2 instances to use imdsv2 unless specified in the config. These changes allow for imdsv2 by using tokens for calls to the metadata service.
- Updated the userdata template to get and use tokens for curl calls to the metadata service
- Updated the `cli53` tool to the latest version
- Added an `instance_refresh` block to the autoscaling group template. The VMs were not always being replaced without this block.
`cli53` has been updated the latest version, `0.8.22`. The tool hasn't been updated since February 2023, so we may want to use a different mechanism to update the bastion's A record, like the aws cli.

imdsv2 configuration

---

aws/Makefile
aws/README.md
aws/ami.tf
aws/bastion-userdata.tmpl
aws/inputs.tf
aws/launchtemplate.tf

This PR fixes #
- custom AMI id option
- uses awscli instead of cli53 to update route53 record
- Option for people who want a different AMI than the default Ubuntu AMI, such as customized/golden AMIs.
- cli53, the tool used to update the Bastion's A record in Route53, has not been updated since 2023. The awscli is already being used for retrieving data from S3, it can also be used to update Route53.
Added an optional variable to use a custom AMI image, and changed the userdata script to use awscli to update the Route53 A record.

route53 record command, custom ami

---

aws/README.md

This PR fixes:
The current documentation does not show how to connect to a private EKS API endpoint.
Provide information for accessing private EKS API endpoints through the bastion.
Added documentation.

Adding private EKS cluster access info
